Countries_SQL_Inefficient=[
'(CASE WHEN Olive_Plan_Line_Name LIKE "%India%" THEN "India"',
'WHEN Olive_Plan_Line_Name LIKE "%United States%" THEN "United States"',
'WHEN Olive_Plan_Line_Name LIKE "%United Kingdom%" THEN "United Kingdom"',
'WHEN Olive_Plan_Line_Name LIKE "%France%" THEN "France"',
'WHEN Olive_Plan_Line_Name LIKE "%Namibia%" THEN "Namibia"',
'WHEN Olive_Plan_Line_Name LIKE "%Germany%" THEN "Germany"',
'WHEN Olive_Plan_Line_Name LIKE "%Japan%" THEN "Japan"',
'WHEN Olive_Plan_Line_Name LIKE "%Vietnam%" THEN "Vietnam"',
'WHEN Olive_Plan_Line_Name LIKE "%Australia%" THEN "Australia"',
'WHEN Olive_Plan_Line_Name LIKE "%Canada%" THEN "Canada"',
'WHEN Olive_Plan_Line_Name LIKE "%Philippines%" THEN "Philippines"',
'WHEN Olive_Plan_Line_Name LIKE "%Turkey%" THEN "Turkey"',
'WHEN Olive_Plan_Line_Name LIKE "%Malaysia%" THEN "Malaysia"',
'WHEN Olive_Plan_Line_Name LIKE "%Thailand%" THEN "Thailand"',
'WHEN Olive_Plan_Line_Name LIKE "%Indonesia%" THEN "Indonesia"',
'WHEN Olive_Plan_Line_Name LIKE "%Italy%" THEN "Italy"',
'WHEN Olive_Plan_Line_Name LIKE "%Spain%" THEN "Spain"',
'WHEN Olive_Plan_Line_Name LIKE "%Russia%" THEN "Russia"',
'WHEN Olive_Plan_Line_Name LIKE "%Singapore%" THEN "Singapore"',
'WHEN Olive_Plan_Line_Name LIKE "%Poland%" THEN "Poland"',
'WHEN Olive_Plan_Line_Name LIKE "%South Africa%" THEN "South Africa"',
'WHEN Olive_Plan_Line_Name LIKE "%Pakistan%" THEN "Pakistan"',
'WHEN Olive_Plan_Line_Name LIKE "%Netherlands%" THEN "Netherlands"',
'WHEN Olive_Plan_Line_Name LIKE "%Ukraine%" THEN "Ukraine"',
'WHEN Olive_Plan_Line_Name LIKE "%Saudi Arabia%" THEN "Saudi Arabia"',
'WHEN Olive_Plan_Line_Name LIKE "%South Korea%" THEN "South Korea"',
'WHEN Olive_Plan_Line_Name LIKE "%Taiwan%" THEN "Taiwan"',
'WHEN Olive_Plan_Line_Name LIKE "%Israel%" THEN "Israel"',
'WHEN Olive_Plan_Line_Name LIKE "%Sweden%" THEN "Sweden"',
'WHEN Olive_Plan_Line_Name LIKE "%Egypt%" THEN "Egypt"',
'WHEN Olive_Plan_Line_Name LIKE "%Denmark%" THEN "Denmark"',
'WHEN Olive_Plan_Line_Name LIKE "%Brazil%" THEN "Brazil"',
'WHEN Olive_Plan_Line_Name LIKE "%Morocco%" THEN "Morocco"',
'WHEN Olive_Plan_Line_Name LIKE "%Nigeria%" THEN "Nigeria"',
'WHEN Olive_Plan_Line_Name LIKE "%Switzerland%" THEN "Switzerland"',
'WHEN Olive_Plan_Line_Name LIKE "%Norway%" THEN "Norway"',
'WHEN Olive_Plan_Line_Name LIKE "%Ireland%" THEN "Ireland"',
'WHEN Olive_Plan_Line_Name LIKE "%Belgium%" THEN "Belgium"',
'WHEN Olive_Plan_Line_Name LIKE "%United Arab Emirates%" THEN "United Arab Emirates"',
'WHEN Olive_Plan_Line_Name LIKE "%Austria%" THEN "Austria"',
'WHEN Olive_Plan_Line_Name LIKE "%Portugal%" THEN "Portugal"',
'WHEN Olive_Plan_Line_Name LIKE "%Hungary%" THEN "Hungary"',
'WHEN Olive_Plan_Line_Name LIKE "%Romania%" THEN "Romania"',
'WHEN Olive_Plan_Line_Name LIKE "%Hong Kong%" THEN "Hong Kong"',
'WHEN Olive_Plan_Line_Name LIKE "%Czech Republic%" THEN "Czech Republic"',
'WHEN Olive_Plan_Line_Name LIKE "%Sri Lanka%" THEN "Sri Lanka"',
'WHEN Olive_Plan_Line_Name LIKE "%New Zealand%" THEN "New Zealand"',
'WHEN Olive_Plan_Line_Name LIKE "%Finland%" THEN "Finland"',
'WHEN Olive_Plan_Line_Name LIKE "%Mexico%" THEN "Mexico"',
'WHEN Olive_Plan_Line_Name LIKE "%Greece%" THEN "Greece"',
'WHEN Olive_Plan_Line_Name LIKE "%Belarus%" THEN "Belarus"',
'WHEN Olive_Plan_Line_Name LIKE "%Lithuania%" THEN "Lithuania"',
'WHEN Olive_Plan_Line_Name LIKE "%Slovenia%" THEN "Slovenia"',
'WHEN Olive_Plan_Line_Name LIKE "%Slovakia%" THEN "Slovakia"',
'WHEN Olive_Plan_Line_Name LIKE "%Bulgaria%" THEN "Bulgaria"',
'WHEN Olive_Plan_Line_Name LIKE "%Algeria%" THEN "Algeria"',
'WHEN Olive_Plan_Line_Name LIKE "%Croatia%" THEN "Croatia"',
'WHEN Olive_Plan_Line_Name LIKE "%Tunisia%" THEN "Tunisia"',
'WHEN Olive_Plan_Line_Name LIKE "%Kenya%" THEN "Kenya"',
'WHEN Olive_Plan_Line_Name LIKE "%Kazakstan%" THEN "Kazakstan"',
'WHEN Olive_Plan_Line_Name LIKE "%Jordan%" THEN "Jordan"',
'WHEN Olive_Plan_Line_Name LIKE "%Estonia%" THEN "Estonia"',
'WHEN Olive_Plan_Line_Name LIKE "%Latvia%" THEN "Latvia"',
'WHEN Olive_Plan_Line_Name LIKE "%Ghana%" THEN "Ghana"',
'WHEN Olive_Plan_Line_Name LIKE "%Moldova Republic of%" THEN "Moldova Republic of"',
'WHEN Olive_Plan_Line_Name LIKE "%Cyprus%" THEN "Cyprus"',
'WHEN Olive_Plan_Line_Name LIKE "%Bangladesh%" THEN "Bangladesh"',
'WHEN Olive_Plan_Line_Name LIKE "%Bosnia & Herzegovina%" THEN "Bosnia & Herzegovina"',
'WHEN Olive_Plan_Line_Name LIKE "%Luxembourg%" THEN "Luxembourg"',
'WHEN Olive_Plan_Line_Name LIKE "%Uganda%" THEN "Uganda"',
'WHEN Olive_Plan_Line_Name LIKE "%Bahrain%" THEN "Bahrain"',
'WHEN Olive_Plan_Line_Name LIKE "%Serbia%" THEN "Serbia"',
'WHEN Olive_Plan_Line_Name LIKE "%Tanzania%" THEN "Tanzania"',
'WHEN Olive_Plan_Line_Name LIKE "%Zimbabwe%" THEN "Zimbabwe"',
'WHEN Olive_Plan_Line_Name LIKE "%Ivory Coast%" THEN "Ivory Coast"',
'WHEN Olive_Plan_Line_Name LIKE "%Ecuador%" THEN "Ecuador"',
'WHEN Olive_Plan_Line_Name LIKE "%Rwanda%" THEN "Rwanda"',
'WHEN Olive_Plan_Line_Name LIKE "%Dominican Republic%" THEN "Dominican Republic"',
'WHEN Olive_Plan_Line_Name LIKE "%Zambia%" THEN "Zambia"',
'WHEN Olive_Plan_Line_Name LIKE "%Jamaica%" THEN "Jamaica"',
'WHEN Olive_Plan_Line_Name LIKE "%Libya%" THEN "Libya"',
'WHEN Olive_Plan_Line_Name LIKE "%Malta%" THEN "Malta"',
'WHEN Olive_Plan_Line_Name LIKE "%Senegal%" THEN "Senegal"',
'WHEN Olive_Plan_Line_Name LIKE "%Costa Rica%" THEN "Costa Rica"',
'WHEN Olive_Plan_Line_Name LIKE "%Guatemala%" THEN "Guatemala"',
'WHEN Olive_Plan_Line_Name LIKE "%Bolivia%" THEN "Bolivia"',
'WHEN Olive_Plan_Line_Name LIKE "%Albania%" THEN "Albania"',
'WHEN Olive_Plan_Line_Name LIKE "%Malawi%" THEN "Malawi"',
'WHEN Olive_Plan_Line_Name LIKE "%Nicaragua%" THEN "Nicaragua"',
'WHEN Olive_Plan_Line_Name LIKE "%Uruguay%" THEN "Uruguay"',
'WHEN Olive_Plan_Line_Name LIKE "%Hondurus%" THEN "Hondurus"',
'WHEN Olive_Plan_Line_Name LIKE "%Democratic Republic of Congo%" THEN "Democratic Republic of Congo"',
'WHEN Olive_Plan_Line_Name LIKE "%Mauritius%" THEN "Mauritius"',
'WHEN Olive_Plan_Line_Name LIKE "%Botswana%" THEN "Botswana"',
'WHEN Olive_Plan_Line_Name LIKE "%Bahamas%" THEN "Bahamas"',
'WHEN Olive_Plan_Line_Name LIKE "%Benin%" THEN "Benin"',
'WHEN Olive_Plan_Line_Name LIKE "%Fiji Islands%" THEN "Fiji Islands"',
'WHEN Olive_Plan_Line_Name LIKE "%Guyana%" THEN "Guyana"',
'WHEN Olive_Plan_Line_Name LIKE "%Mali%" THEN "Mali"',
'WHEN Olive_Plan_Line_Name LIKE "%Barbados%" THEN "Barbados"',
'WHEN Olive_Plan_Line_Name LIKE "%Madagascar%" THEN "Madagascar"',
'WHEN Olive_Plan_Line_Name LIKE "%Guinea%" THEN "Guinea"',
'WHEN Olive_Plan_Line_Name LIKE "%Chad%" THEN "Chad"',
'WHEN Olive_Plan_Line_Name LIKE "%Djibouti%" THEN "Djibouti"',
'WHEN Olive_Plan_Line_Name LIKE "%Burundi%" THEN "Burundi"',
'WHEN Olive_Plan_Line_Name LIKE "%US%" THEN "United States"',
'WHEN Olive_Plan_Line_Name LIKE "%CA%" THEN "Canada"',
'WHEN Olive_Plan_Line_Name LIKE "%JP %" THEN "Japan"',
'WHEN Olive_Plan_Line_Name LIKE "%[US]%" THEN "United States"',
'WHEN Olive_Plan_Line_Name LIKE "%[CA]%" THEN "Canada"',
'WHEN Olive_Plan_Line_Name LIKE "%JP%" THEN "Japan"'

]


Countries_SQL_Efficient=[]
for item in Countries_SQL_Inefficient:
    START =item.find("THEN ")+6
    END = NAME.find('"')
    NAME = item[START:END]
    Countries_SQL_Efficient.append("Olive_Plan_Line_Name LIKE '%" + NAME + "%' " + "OR Olive_Plan_Name LIKE '%" + NAME + "%' " + "OR Olive__Campaign_Name LIKE '%" + NAME + "%'"+ " THEN " + "'" + NAME +"'" )
Countries_SQL_Efficient
